### ISSUE TITLE
Initial project setup & kobo setup

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/COVIDaction#1]
- [x] Create a project on openfn.org
- [x] Grant support access
- [x] Request an enterprise plan from @taylordowns2000 
- [x] Connect this github repo (`main` branch, autodeploy on)
- [x] Setup a KoboToolbox form (ask @aleksa-krolls for an example form or existing project)
- [x] Setup data forwarding from Kobo to your OpenFn project - see OpenFn docs/ what you did before for the [RET Demo](https://www.openfn.org/projects/p5y37m/jobs)
- [x] Submit form data to Kobo
- [x] Copy message body from inbox to `sampleData` folder
- [x] Create "Submission received" trigger in openfn project which matches your kobo form submission
- [ ] Update the Kobo docs page as you go: https://github.com/OpenFn/docs/blob/develop/docs/apps/kobo-toolbox.md

**Comment by aleksa-krolls** [comment]
@daissatou for the Kobo project setup, see LP for `openfn_kobo` to access our demo Kobo account. You can then use this form to integrate with a new OpenFn project: https://kf.kobotoolbox.org/#/forms/a69YusHs8arP7VxxFSTpuj/landing

**Comment by daissatou** [comment]
Done :)

**Comment by daissatou** [comment]
@taylordowns2000 FYI

**Comment by taylordowns2000** [comment]
Thanks, that's fantastic. @daissatou , are any changes/updates going to be made to the Kobo docs page or can I close this issue?
![image](https://user-images.githubusercontent.com/8732845/109974967-01db2100-7cf2-11eb-8946-c5d75c52bfa7.png)
