### ISSUE TITLE
DHIS2 job setup

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/COVIDaction#2]
- [x] review sample data from Kobo submission (@daissatou will provide this - wait for updates)
- [ ] create new dhis2 play credential (@jedbgold , ask @chaiwa-berian for the right login info here!)
- [x] create new job, filepath = `dhis2.js`
- [x] write expression that creates a new tracked entity instance for each kobo submission
- [ ] test job on openfn.org to ensure it's working

**Comment by chaiwa-berian** [comment]
@taylordowns2000 and @daissatou Is there sample data from Kobo, for this issue?

**Comment by taylordowns2000** [comment]
@chaiwa-berian , just added you to the project: https://openfn.org/projects/pd7qw7/messages - take the latest message as sample

**Comment by taylordowns2000** [comment]
Howdy @chaiwa-berian , can you check out why this is failing and make the necessary changes?

https://openfn.org/projects/pd7qw7/runs/rn5r68bb
