### ISSUE TITLE
Salesforce job setup

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/COVIDaction#3]
Goal is to create 1 `Contact` record for every Kobo submission.
- [x] review sample data from Kobo submission
- [x] create new job, filepath = `salesforce.js`
- [x] create new credential (see LP for `Salesforce Dev Org`)
- [x] write expression that creates a new `Contact` in salesforce for each kobo submission... you may need to ask @aleksa-krolls for help for configuring other Salesforce fields beyond name
- [x] test job on openfn.org to ensure it's working

**Comment by daissatou** [comment]
This is complete. You can take a look here: https://www.openfn.org/projects/pd7qw7/jobs/jv4ezx

**Comment by daissatou** [comment]
@taylordowns2000 FYI
